### ISSUE TITLE
ModuleNotFoundError: No module named 'jnius'

### ISSUE THREAD

**Issue by ghost** [kivy/kivy-launcher#13]
I just downloads the kivy launcher source code from here https://github.com/kivy/kivy-launcher
and I want to test on my pc but I get this error 
it's possible to run it on the pc or I missing some things 

```
C:\Users\husam\OneDrive\Desktop\Folders\kivy-launcher-master>python main.py
dispathc!
Traceback (most recent call last):
  File "main.py", line 31, in dispatch
    from jnius import autoclass
ModuleNotFoundError: No module named 'jnius'
[INFO   ] [Logger      ] Record log in C:\Users\husam\.kivy\logs\kivy_20-05-15_4.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\husam\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\husam\AppData\Local\Programs\Python\Python37\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
start of log
 Traceback (most recent call last):
   File "main.py", line 62, in <module>
     dispatch()
   File "main.py", line 58, in dispatch
     run_launcher()
   File "main.py", line 17, in run_launcher
     Launcher().run()
   File "C:\Users\husam\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 829, in run
     root = self.build()
   File "C:\Users\husam\OneDrive\Desktop\Folders\kivy-launcher-master\launcher\app.py", line 188, in build
     from jnius import autoclass
 ModuleNotFoundError: No module named 'jnius'
```

**Comment by tshirtman** [comment]
you can try installing pyjnius with pip, i think it should work (running the launcher) but of course features that use pyjnius to access android features won't work on desktop..
